apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sampleapp-servicemonitor
  labels:
    app: sampleapp
    release: prometheus
spec:
  selector:
    matchLabels:
      app: sampleapp
  endpoints:
  - port: metrics
    interval: 15s